### ISSUE TITLE
high I/O on experimental backends

### ISSUE THREAD

**Issue by aspieln3r** [tryone144/compton#31] opened 2020-03-14 05:44 UTC
Platform: Arch linux amd64 

GPU, drivers, and screen setup: Intel UHD Graphics 620, laptop 

Compton version: 1328_Next.47.g7eebdbc_2020.03.12-1

Compton configuration: https://pastebin.com/J9w4WUbU

### Steps of reproduction
run picom with --experimental-backends
see iotop
picom is frequently on top
issue is not present without --experimental-backends

### Expected behavior
no changes on io load on both run modes

### Current Behavior & Other details
https://imgur.com/NhXJJqI

**Comment by tryone144** [comment] 2020-03-31 12:14
Does this issue persist when using a different blur algorithm and `--experimental-backends`?
I can't reproduce this on my setup (official Nvidia drivers here).

**Comment by aspieln3r** [comment] 2020-03-31 14:45
I opened same issue here : https://github.com/yshui/picom/issues/341
On my laptop, this issue is not there when using nvidia dGPU with PRIME.
So, issue is persistent only in intel iGPU.

**Comment by tryone144** [comment] 2020-03-31 14:53
Thanks. I'll close this issue then.

**Closed as completed by tryone144** 2020-03-31 14:53 UTC
Labels: upstream
