### ISSUE TITLE
Mpv blur issue

### ISSUE THREAD

**Issue by farzads2** [tryone144/compton#4] opened 2019-01-26 16:36 UTC
Platform: Arch linux

GPU, drivers, : NVidia GTX 970, nvidia-drivers 415.27

Compton version: compton-tryone-git 0.1_beta2.95.g241bbc5-1

Compton configuration:https://pastebin.com/WFzUs83L

### Steps of reproduction

Launching mpv and playing videos.

### Expected behavior

No transparency should be present.

### Current Behavior & Other details
 
There is a transparent border on upper mpv window .
I have tried using opaque exclude rule but didn't work .

![screenshot_20190126_192735](https://user-images.githubusercontent.com/4690369/51790041-79e6cc80-21a5-11e9-90d5-3952b8750a64.jpeg)

**Comment by tryone144** [comment] 2019-01-26 17:07
Hi,
what WM or DE are you using? The frame looks like it's drawn by your Window Manager.

The transparent frame should be due to the `frame-opacity = 0.3;` rule in line 17. And `blur-background-frame = false;` in line 55 should disable blurring the transparent frame. Maybe try commenting out line 17 and see if the border changes transparency with the window itself.

I currently can't reproduce this as my i3 is drawing window frames differently, so the `frame-opacity` rule has no effect.

**Comment by farzads2** [comment] 2019-01-26 17:51
Hi,
I am using I3-gaps.
Commenting out line 17 fixed the issue.
Thanks.

**Comment by tryone144** [comment] 2019-01-26 17:54
Great! I am not sure, but there might actually be a way to change it's value similarily to the normal window opacity. If you actually want transparent frames for windows. Maybe the original Manpage/Readme includes so info.

Closing this.

**Closed as completed** 2019-01-26 17:54 UTC
